[package]
name = "resultgetter"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda_runtime = "0.2"
lambda_http = "0.1"
serde = "1.0"
serde_json = "1.0"
chrono = "0.4"
bson = "0.14"
db = { path = "../db" }
