[package]
name = "util"
version = "0.1.0"
edition = "2018"

[lib]
name = "util"
path = "src/lib.rs"

[dependencies]
rusoto_core = "0.43"
rusoto_secretsmanager = "0.43"
tokio = "0.2"
serde_json = "1.0"