[package]
name = "db"
version = "0.1.0"
edition = "2018"

[lib]
name = "db"
path = "src/lib.rs"

[dependencies]
bson = "0.14"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
util = { path = "../util" }

[dependencies.mongodb]
version = "0.10.0"
default-features = false
features = ["sync"]
